# Site settings
title: 小光头的OData私房菜
email: yi.ding.cn@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  轻松愉快的开放数据协议（OData）教程
baseurl: "/odata" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
highlighter: rouge

permalink: /:title/